### ISSUE TITLE
Cannot build solution

### ISSUE THREAD

**Issue by jochem4207** [danroth27/BlazorNet5Samples#2]
At first, thank you for this amazing reference project! 

The solution doesn't build (in latest vs 2019 preview)

![image](https://user-images.githubusercontent.com/4976335/95908560-8823b480-0d9d-11eb-92cd-0151d2111128.png)

1) ProtectedBrowser storage recently moved to ASP.NET Core shared framework.
https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore

2) I managed to get the json error gone by updating the one package that was update-able (including previews). 

Just as tip for others ^

**Comment by danroth27** [comment]
Should be fixed now. Thanks!

**Comment by jochem4207** [comment]
Confirmed, works perfectly, thank you !
